services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: adrianklik1998
    volumes:
      - pgdata:/var/lib/postgresql/data 
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
 
volumes:
  pgdata: