services:
  postgres:
    image: postgres:latest # if it's production ready we never use latest
    container_name: postgres-test
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password123!
      POSTGRES_DB: klikInc
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

# https://hub.docker.com/r/prometheuscommunity/postgres-exporter

volumes:
  postgres_data: