global:
  scrape_interval: 15s

rule_files:
  - "alerts.yml" # Upewnij się, że ten plik istnieje w katalogu projektu

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "postgres_exporter"
    static_configs:
      - targets: ["postgres_exporter:9187"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]
